FROM node:20-alpine

WORKDIR /web

# Instala dependências
COPY package.json package-lock.json* ./
RUN npm install --no-audit --no-fund

# Expõe porta do Vite
EXPOSE 5173

# Comando padrão (será sobrescrito pelo docker-compose)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

